package monopoly.resto;

public class Valor {
    public static final int COSTE_INICIAL = 100000;
    public static final int COSTE_GRUPO1 = COSTE_INICIAL;
    public static final int ALQUILER_GRUPO1 = COSTE_INICIAL / 2;
    public static final int COSTE_GRUPO2 = (int) (COSTE_GRUPO1 * 1.3);
    public static final int ALQUILER_GRUPO2 = COSTE_GRUPO2 / 2;
    public static final int COSTE_GRUPO3 = (int) (COSTE_GRUPO2 * 1.3);
    public static final int ALQUILER_GRUPO3 = COSTE_GRUPO3 / 2;
    public static final int COSTE_GRUPO4 = (int) (COSTE_GRUPO3 * 1.3);
    public static final int ALQUILER_GRUPO4 = COSTE_GRUPO4 / 2;
    public static final int COSTE_GRUPO5 = (int) (COSTE_GRUPO4 * 1.3);
    public static final int ALQUILER_GRUPO5 = COSTE_GRUPO5 / 2;
    public static final int COSTE_GRUPO6 = (int) (COSTE_GRUPO5 * 1.3);
    public static final int ALQUILER_GRUPO6 = COSTE_GRUPO6 / 2;
    public static final int COSTE_GRUPO7 = (int) (COSTE_GRUPO6 * 1.3);
    public static final int ALQUILER_GRUPO7 = COSTE_GRUPO7 / 2;
    public static final int COSTE_GRUPO8 = (int) (COSTE_GRUPO7 * 1.3);
    public static final int ALQUILER_GRUPO8 = COSTE_GRUPO8 / 2;
    public static final int FORTUNA_INICIAL = 500000;
    public static final String MARRON = "MARRON";
    public static final String CYAN = "CYAN";
    public static final String ROSA = "ROSA";
    public static final String NARANJA = "NARANJA";
    public static final String ROJO = "ROJO";
    public static final String AMARILLO = "AMARILLO";
    public static final String VERDE = "VERDE";
    public static final String AZUL = "AZUL";
    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_NEGRO = "\u001B[30m";
    public static final String ANSI_ROJO = "\u001B[31m";
    public static final String ANSI_VERDE = "\u001B[32m";
    public static final String ANSI_AMARILLO = "\u001B[33m";
    public static final String ANSI_AZUL = "\u001B[34m";
    public static final String ANSI_MORADO = "\u001B[35m";
    public static final String ANSI_CYAN = "\u001B[36m";
    public static final String ANSI_BLANCO = "\u001B[37m";
    public static final String SOLAR1_GRUPO1 = "Orgrimmar";
    public static final String SOLAR2_GRUPO1 = "Ventormenta";
    public static final String SOLAR1_GRUPO2 = "Lunargenta";
    public static final String SOLAR2_GRUPO2 = "Entrañas";
    public static final String SOLAR3_GRUPO2 = "Cima del Trueno";
    public static final String SOLAR1_GRUPO3 = "Forjaz";
    public static final String SOLAR2_GRUPO3 = "Darnassus";
    public static final String SOLAR3_GRUPO3 = "Exodar";
    public static final String SOLAR1_GRUPO4 = "Dalaran";
    public static final String SOLAR2_GRUPO4 = "Bosque Cancion Eterna";
    public static final String SOLAR3_GRUPO4 = "Bosque de Elwynn";
    public static final String SOLAR1_GRUPO5 = "Claros de Tirisfal";
    public static final String SOLAR2_GRUPO5 = "Durotar";
    public static final String SOLAR3_GRUPO5 = "Vallefresno";
    public static final String SOLAR1_GRUPO6 = "Laderas de Trabalomas";
    public static final String SOLAR2_GRUPO6 = "Montañas de Alterac";
    public static final String SOLAR3_GRUPO6 = "Tierras Altas de Arathi";
    public static final String SOLAR1_GRUPO7 = "Frondavil";
    public static final String SOLAR2_GRUPO7 = "Costa Oscura";
    public static final String SOLAR3_GRUPO7 = "Los Baldios";
    public static final String SOLAR1_GRUPO8 = "Crater de Un'Goro";
    public static final String SOLAR2_GRUPO8 = "Corona de Hielo";


}
